### ISSUE TITLE
Refactor: simplify some functions

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#109]
Currently flake8 reports the following functions which are too complex:
![изображение](https://user-images.githubusercontent.com/39452697/90312454-43021400-df0d-11ea-80ac-ae75c9799257.png)
It would be good to refactor those functions into multiple smaller ones, especially `model_view`.

**Comment by xiaoxianma** [comment]
I'd like to pick this up if no one is working on this.

**Comment by MrNaif2018** [comment]
Thank you! I will be able to help understanding why some things were designed so at the beginning (:
