### ISSUE TITLE
Do we need to switch to starlette? (Community decision)

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#54]
[Starlette](https://www.starlette.io/) is a light ASGI framework and toolchain, modular and extendable.
It is ASGI, so it is 100% faster than django, it is one of the fastest even from ASGI frameworks(faster than good old aiohttp too)
We can switch to it fully, or use it in only some parts of our application(websockets, background tasks), or don't switch at all.
Check out their docs, it shows what starlette is.
It is a community decision, leave your opinions here.

**Comment by ayekyk** [comment]
Well, they say that _"Starlette ... is ideal for building high performance asyncio services"_, so If somebody will use bitcart in highload environments, this will give a bit more performance.

**Comment by MrNaif2018** [comment]
I think we will migrate to fastapi, it is based on starlette.
I see 2 possible ways:
django+drf+django templates(now)->django+drf+jinja2(faster template engine, used by all other frameworks)->fastapi+jinja2->fastapi+nuxt.js
or
django+drf+django templates->fastapi+jinja2
or
django+drf+django templates->fastapi+nuxt.js
There are shorter ways, or longer ones. What are your thoughts?

**Comment by MrNaif2018** [comment]
I guess we will switch to fastapi, closing this.
