### ISSUE TITLE
Add authentification to API

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#76]
Our bitcart backend API is written in fastapi.
It is located in `main.py` file and` api/` folder.
Currently it is accessible by everyone.
We should add authentification, either Token, or JWT, or some other kind of auth.
Some useful links:
https://fastapi.tiangolo.com/tutorial/security/intro/
https://fastapi.tiangolo.com/tutorial/security/get-current-user/
https://fastapi.tiangolo.com/tutorial/security/first-steps/
https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/

The user model is defined in `schemes.py`(pydantic validation for output in API), and database model in `models.py`.
Also, when user is logged in API should be restricted  to displaying only those wallets, store, products, invoices that user have.
User has is_superuser value, if it is `True`, then all data should be displayed.
If user is not superuser, users list might not be accessible at all, or there should be a new endpoint added:
`/users/current`
Or `/profile`
Returning logged user info.

**Comment by hmuhammadazeem** [comment]
Hey! I would like to give it a shot.

**Comment by MrNaif2018** [comment]
Thanks a lot! Feel free to ask any questions you got during implementing that

**Comment by MrNaif2018** [comment]
@hmuhammadazeem Do you need any help in understanding the repo or how to contribute? Ask questions if any, we can discuss further details of implementation here.

**Comment by hmuhammadazeem** [comment]
Hey! I'm going with JWT. I'll get to you if I've any questions.

**Comment by hmuhammadazeem** [comment]
Hey, there is a /token end point. What is that for? Is it for auth? Or should I create my own for auth? And the code isn't working locally for me. Error is in model_view method on line 144. Error says: re.error: unbalanced parenthesis at position 26

**Comment by MrNaif2018** [comment]
`re.error`? I don't use regex or anything like so.
What is your python version?
/token endpoint is POST endpoint to create a token, you submit username and password, and if it is valid, it created token for that user(`os.urandom(32).hex()`).
It is just a usual token, so you might need to change that if needed.

**Comment by hmuhammadazeem** [comment]
Yea, you don't but fastapi does it. 
Well, I'm still trying to at least code it right. And as /token point is just for creation. So, I'll adjust it to use pyJWT. And might also add an expiry column for token.
- How do I apply auth on endpoint such as "/products". These are dynamically added. Can you point to any reference?

**Comment by MrNaif2018** [comment]
You should edit model_view code in utils.py, it generates views.
Like `async def post` is for post request https://github.com/MrNaif2018/bitcart/blob/master/api/utils.py#L92
But in general, for this model_view function I would add additional `apply_auth` or just `auth=True/False` which will turn on/off auth. Also having a decorator like @auth_required would be good.

**Comment by hmuhammadazeem** [comment]
I didn't get `auth=True/False` thing. 
Should I just wrap individual functions defined inside `model_view` with decorator or some auth check?

**Comment by MrNaif2018** [comment]
I mean make model_view function accept additional boolean parameter:
I think you can do like 
```
if auth: 
    # enable auth somehow
```
Decorator is not for model_view, but just additional convience thing to use in usual views.
```
def model_view(
    router: APIRouter,
    path: str,
    orm_model,
    pydantic_model,
    create_model=None,
    allowed_methods: List[str] = ["GET_ONE"] + HTTP_METHODS,
    custom_methods: Dict[str, Callable] = {},
    background_tasks_mapping: Dict[str, Callable] = {},
    auth: bool = False
):
```

**Comment by MrNaif2018** [comment]
One tip, when developing, start api with
`uvicorn --reload main:app`
To get automatic code reloading!

**Comment by MrNaif2018** [comment]
So, @hmuhammadazeem, do you take on this issue or I can do that myself?
If you've encountered any problems, report them there and we will resolve them.

**Comment by hmuhammadazeem** [comment]
I'm still on it. If I get stuck I'll let you know if I want to continue or take help.

**Comment by MrNaif2018** [comment]
@hmuhammadazeem Could you please open your WIP(Work in Progress) PR with your changes so that we can keep track on the progress?

**Comment by hmuhammadazeem** [comment]
Hey, till now I've been unable to progress much on this. Multiple reasons. Can you do some working on it yourself? I'll like to observe and learn. Thanks.

**Comment by MrNaif2018** [comment]
Of course, yesterday I created it,will open PR for you to see how I did that.

**Comment by MrNaif2018** [comment]
Check the PR here: #87

**Comment by MrNaif2018** [comment]
We need to decide actually.
Do we need JWT at all or not?
We can just store tokens in redis or postgres, and have a /login and /logout endpoints.
Frontend would just store that in localStorage.
It would allow revoking tokens and logging out from all devices

**Comment by MrNaif2018** [comment]
Authentification has been added! A lot of job done, now we need to do some additional improvements in UI and API!
