### ISSUE TITLE
Add alembic migrations to the project

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#77]
Bitcart backend API uses gino orm(kind of orm), which is executing sqlalchemy core queries via async database driver.
But there are no migrations yet, so user data might be broken if we won't add migrations.
All is needed is to setup alembic with that project, and add applying migrations code somewhere in [`docker-entrypoint.sh`](https://github.com/MrNaif2018/bitcart-docker/blob/master/compose/scripts/docker-entrypoint.sh).
But as bitcart is using async orm, we might need to find alternate solution for that if it is possible.
Also any ideas on using a better orm are appreciated.
In future we might switch to edgedb at all.

**Comment by tomasmor42** [comment]
Hi! Picking this one up.

**Comment by MrNaif2018** [comment]
Thanks! Feel free to ask any questions!

**Comment by MrNaif2018** [comment]
It is supposed to be run with main repo, yes.
If you have any suggestions to improve it, you're welcome.
You can run the commands manually:
```
git clone https://github.com/tomasmor42/bitcart compose/bitcart
cd compose/bitcart
cat > conf/.env << EOF
DB_HOST=database
CHANNEL_LAYERS_HOST=redis://redis
CACHE_REDIS_URL=redis://redis
DRAMATIQ_REDIS_URL=redis://redis
RPC_URL=http://daemon:5000
EOF
cd ../..
```

About docker entrypoint, it is started after the database is ready, if it is not, docker will retry until success.
I am not sure about custom script as it needs database to be running in docker.

**Comment by tomasmor42** [comment]
This thing I managed to do myself, but after that I run `docker-compose -f compose/generated.yml up --build` and it indeed starts the application, but with original repo. 
So far I will open a PR for the main project.
If you think early start won't be an issue, it's perfect.

**Comment by MrNaif2018** [comment]
Thanks a lot! Will add to docker myself! Closing this.
Also, have you experienced any difficulties during contribution? Could you please tell me which to improve the docs?

**Comment by tomasmor42** [comment]
Great! Thanks a lot! 
Well, except my difficulties with Docker -- not really, everything was pretty clear about the setting the local environment and the project itself.

**Comment by MrNaif2018** [comment]
Thank you again! Will update docker development docs.
