### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by manzaa739** [MrNaif2018/bitcart#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. master branch]

**Additional context**

**Comment by manzaa739** [comment]
ว

**Comment by MrNaif2018** [comment]
What is the bug even? Could you please describe in details which bug did you meet?

**Comment by MrNaif2018** [comment]
Closing this for the lack of information. If you have a real issue, reopen it with more details.
